/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "2fa_checkbox": {                                "en": "2-step verification",                             "de": "2-stufige Überprüfung",                           "ru": "Двухэтапная авторизация",                         "pt": "Verificação em duas etapas",                      "nl": "Authenticatie in twee stappen",                   "fr": "Vérification en 2 étapes",                        "it": "Verifica in due passaggi",                        "es": "Verificación en 2 pasos",                         "pl": "Weryfikacja dwuetapowa",                          "zh-cn": "两步验证"},
    "2fa_code": {                                    "en": "Secret key for 2-step verification",              "de": "Geheimschlüssel für die Bestätigung in zwei Schritten", "ru": "Секретный ключ для двухэтапной проверки",         "pt": "Chave secreta para verificação em duas etapas",   "nl": "Geheime sleutel voor authenticatie in twee stappen", "fr": "Clé secrète pour la vérification en 2 étapes",    "it": "Chiave segreta per la verifica in due passaggi",  "es": "Clave secreta para la verificación en dos pasos", "pl": "Tajny klucz do weryfikacji dwuetapowej",          "zh-cn": "两步验证的密钥"},
    "as": {                                          "en": "Audio Station",                                   "de": "Audio Station",                                   "ru": "Audio Station",                                   "pt": "Audio Station",                                   "nl": "Audio Station",                                   "fr": "Audio Station",                                   "it": "Audio Station",                                   "es": "Audio Station",                                   "pl": "Audio Station",                                   "zh-cn": "Audio Station"},
    "def": {                                         "en": "default (5000)",                                  "de": "Standard (5000)",                                 "ru": "по умолчанию (5000)",                             "pt": "padrão (5000)",                                   "nl": "standaard (5000)",                                "fr": "par défaut (5000)",                               "it": "impostazione predefinita (5000)",                 "es": "predeterminado (5000)",                           "pl": "domyślnie (5000)",                                "zh-cn": "默认值（5000）"},
    "dl": {                                          "en": "Download Station",                                "de": "Download Station",                                "ru": "Download Station",                                "pt": "Download Station",                                "nl": "Download Station",                                "fr": "Download Station",                                "it": "Download Station",                                "es": "Download Station",                                "pl": "Download Station",                                "zh-cn": "下载站"},
    "getservices": {                                 "en": "Receive data from services",                      "de": "Daten von Diensten empfangen",                    "ru": "Получать данные от сервисов",                     "pt": "Receber dados de serviços",                       "nl": "Ontvang gegevens van services",                   "fr": "Recevoir des données des services",               "it": "Ricevi dati dai servizi",                         "es": "Recibir datos de servicios",                      "pl": "Otrzymuj dane z usług",                           "zh-cn": "从服务接收数据"},
    "getservicesdesc": {                             "en": "If the package is not installed on the NAS, it will still be skipped.", "de": "Wenn das Paket nicht auf dem NAS installiert ist, wird es trotzdem übersprungen.", "ru": "Если пакет не установлен на NAS, он все равно будет пропущен.", "pt": "Se o pacote não estiver instalado no NAS, ele ainda será ignorado.", "nl": "Als het pakket niet op de NAS is geïnstalleerd, wordt het nog steeds overgeslagen.", "fr": "Si le package n'est pas installé sur le NAS, il sera toujours ignoré.", "it": "Se il pacchetto non è installato sul NAS, verrà comunque ignorato.", "es": "Si el paquete no está instalado en el NAS, aún se omitirá.", "pl": "Jeśli pakiet nie zostanie zainstalowany na serwerze NAS, nadal będzie pomijany.", "zh-cn": "如果该程序包未安装在NAS上，仍将被跳过。"},
    "host": {                                        "en": "IP address",                                      "de": "IP-Adresse",                                      "ru": "IP адрес",                                        "pt": "endereço de IP",                                  "nl": "IP adres",                                        "fr": "adresse IP",                                      "it": "indirizzo IP",                                    "es": "dirección IP",                                    "pl": "adres IP",                                        "zh-cn": "IP地址"},
    "https:": {                                      "en": "https",                                           "de": "https",                                           "ru": "HTTPS",                                           "pt": "https",                                           "nl": "https",                                           "fr": "https",                                           "it": "https",                                           "es": "https",                                           "pl": "https",                                           "zh-cn": "https"},
    "login": {                                       "en": "User name",                                       "de": "Nutzername",                                      "ru": "Имя пользователя",                                "pt": "Nome do usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
    "on save adapter restarts with new config immediately": {"de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями"},
    "password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "polling": {                                     "en": "Parameter polling time (ms)",                     "de": "Parameterabrufzeit (ms)",                         "ru": "Время опроса параметра (мс)",                     "pt": "Tempo de pesquisa de parâmetro (ms)",             "nl": "Parameter pollingtijd (ms)",                      "fr": "Temps d'interrogation des paramètres (ms)",       "it": "Tempo di polling dei parametri (ms)",             "es": "Tiempo de sondeo de parámetros (ms)",             "pl": "Czas odpytywania parametru (ms)",                 "zh-cn": "参数轮询时间（毫秒）"},
    "port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "Порт",                                            "pt": "porta",                                           "nl": "haven",                                           "fr": "Port",                                            "it": "porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "slowPollingTime": {                             "en": "Polling time for additional parameters (ms)",     "de": "Abfragezeit für zusätzliche Parameter (ms)",      "ru": "Время опроса для дополнительных параметров (мс)", "pt": "Tempo de pesquisa para parâmetros adicionais (ms)", "nl": "Polling-tijd voor aanvullende parameters (ms)",   "fr": "Temps d'interrogation pour les paramètres supplémentaires (ms)", "it": "Tempo di polling per parametri aggiuntivi (ms)",  "es": "Tiempo de sondeo para parámetros adicionales (ms)", "pl": "Czas odpytywania dla dodatkowych parametrów (ms)", "zh-cn": "附加参数的轮询时间（毫秒）"},
    "ss": {                                          "en": "Surveillance Station",                            "de": "Surveillance Station",                            "ru": "Surveillance Station",                            "pt": "Surveillance Station",                            "nl": "Surveillance Station",                            "fr": "Surveillance Station",                            "it": "Surveillance Station",                            "es": "Surveillance Station",                            "pl": "Surveillance Station",                            "zh-cn": "监控站"},
    "ssh_port": {                                    "en": "SSH port (for Reboot and Shutdown)",              "de": "SSH-Port (für Neustart und Herunterfahren)",      "ru": "Порт SSH (для перезагрузки и выключения)",        "pt": "Porta SSH (para reinicialização e desligamento)", "nl": "SSH-poort (voor opnieuw opstarten en afsluiten)", "fr": "Port SSH (pour le redémarrage et l'arrêt)",       "it": "Porta SSH (per riavvio e spegnimento)",           "es": "Puerto SSH (para reiniciar y apagar)",            "pl": "Port SSH (do ponownego uruchamiania i zamykania)", "zh-cn": "SSH 端口（用于重启和关机）"},
    "version": {                                     "en": "api Version",                                     "de": "API-Version",                                     "ru": "Версия API",                                      "pt": "Versão da API",                                   "nl": "API-versie",                                      "fr": "Version api",                                     "it": "Versione API",                                    "es": "Versión api",                                     "pl": "Wersja interfejsu API",                           "zh-cn": "api版本"},
};